/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Problems = {
  heading?: string;
  rows?: Array<{
    _key: string;
  } & ProblemRow>;
};

export type Offerings = {
  heading?: string;
  intro?: string;
  items?: Array<{
    _key: string;
  } & FeatureItem>;
};

export type Stack = {
  intro?: string;
  groups?: Array<{
    _key: string;
  } & ChipGroup>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type EcosystemCompany = {
  _id: string;
  _type: "ecosystemCompany";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  focus?: string;
  line?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  url?: string;
  relationshipConfirmed?: boolean;
  confirmedBy?: string;
  confirmedOn?: string;
  evidence?: string;
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type ClientLogo = {
  _id: string;
  _type: "clientLogo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  row?: "banking" | "telecom-healthcare-energy";
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  permissionConfirmed?: boolean;
  confirmedBy?: string;
  confirmedOn?: string;
  evidence?: string;
  order?: number;
};

export type IndustryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "industry";
};

export type CapabilityReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "capability";
};

export type CaseStudy = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  allowSlugChange?: boolean;
  anonymisedDescriptor?: string;
  clientPermission?: {
    confirmed?: boolean;
    confirmedBy?: string;
    confirmedOn?: string;
    evidence?: string;
    clientName?: string;
  };
  industry?: IndustryReference;
  capabilities?: Array<{
    _key: string;
  } & CapabilityReference>;
  summary?: string;
  photo?: ImageWithAlt;
  challenge?: TextBlock;
  approach?: TextBlock;
  outcomes?: Array<{
    _key: string;
  } & Stat>;
  quotes?: Array<{
    text?: string;
    attribution?: string;
    confirmed?: boolean;
    confirmedBy?: string;
    confirmedOn?: string;
    evidence?: string;
    _type: "quote";
    _key: string;
  }>;
  publishedAt?: string;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noindex?: boolean;
};

export type TextBlock = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: never;
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  decorative?: boolean;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type LocationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "location";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Opportunity = {
  _id: string;
  _type: "opportunity";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  status?: "open" | "closed";
  slug?: Slug;
  allowSlugChange?: boolean;
  reference?: string;
  team?: "capability" | "client-partnership";
  capability?: CapabilityReference;
  locations?: Array<{
    _key: string;
  } & LocationReference>;
  place?: string;
  remote?: boolean;
  workMode?: "On-site" | "Hybrid" | "Remote";
  employmentType?: "Full-time" | "Part-time" | "Fixed-term" | "Internship";
  experience?: string;
  postedAt?: string;
  closesAt?: string;
  summary?: string;
  description?: ArticleBody;
  requirements?: Array<string>;
  skills?: Array<string>;
  jdPdf?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  applyMethod?: "email" | "link";
  applyEmail?: string;
  applyUrl?: string;
  seo?: Seo;
};

export type ArticleBody = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  _key: string;
} & ImageWithAlt | {
  _key: string;
} & Table | {
  _key: string;
} & Callout>;

export type Location = {
  _id: string;
  _type: "location";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  city?: string;
  short?: string;
  country?: string;
  role?: string;
  text?: string;
  address?: string;
  phone?: string;
  email?: string;
  timeZone?: string;
  locale?: string;
  position?: {
    lat?: number;
    lon?: number;
  };
  link?: LinkItem;
  order?: number;
};

export type LinkItem = {
  _type: "linkItem";
  label?: string;
  href?: string;
};

export type Capability = {
  _id: string;
  _type: "capability";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  heading?: string;
  descriptor?: string;
  slug?: Slug;
  line?: string;
  photo?: ImageWithAlt;
  pageTitle?: string;
  lede?: string;
  points?: Array<string>;
  problems?: Problems;
  offerings?: Offerings;
  stack?: Stack;
  outcomes?: Array<{
    _key: string;
  } & Stat>;
  faq?: Array<{
    _key: string;
  } & FaqItem>;
  team?: string;
  howItWorks?: {
    heading?: string;
    intro?: string;
    steps?: Array<{
      title?: string;
      text?: string;
      note?: string;
      _type: "processStep";
      _key: string;
    }>;
  };
  industryNotes?: Array<{
    industry?: IndustryReference;
    text?: string;
    _type: "industryNote";
    _key: string;
  }>;
  seo?: Seo;
};

export type Industry = {
  _id: string;
  _type: "industry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  short?: string;
  summary?: string;
  photo?: ImageWithAlt;
  hero?: string;
  lede?: string;
  points?: Array<string>;
  challenge?: string;
  build?: string;
  outcome?: string;
  metric?: Stat;
  problems?: Problems;
  offerings?: Offerings;
  stack?: Stack;
  outcomes?: Array<{
    _key: string;
  } & Stat>;
  faq?: Array<{
    _key: string;
  } & FaqItem>;
  capabilityNotes?: Array<{
    capability?: CapabilityReference;
    text?: string;
    _type: "capabilityNote";
    _key: string;
  }>;
  seo?: Seo;
};

export type Stat = {
  _type: "stat";
  value?: string;
  label?: string;
  confirmed?: boolean;
  confirmedBy?: string;
  confirmedOn?: string;
  evidence?: string;
};

export type PageSettings = {
  _id: string;
  _type: "pageSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  page?: string;
  hero?: PageHero;
  faqIntro?: SectionIntro;
  faq?: Array<{
    _key: string;
  } & FaqItem>;
  seo?: Seo;
};

export type SectionIntro = {
  _type: "sectionIntro";
  eyebrow?: string;
  heading?: string;
  intro?: string;
};

export type PageHero = {
  _type: "pageHero";
  eyebrow?: string;
  title?: string;
  lede?: string;
  points?: Array<string>;
  photo?: ImageWithAlt;
};

export type InsightReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "insight";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    badge?: string;
    heading?: string;
    highlight?: string;
    lede?: string;
    points?: Array<string>;
    careersPrompt?: string;
  };
  reel?: Array<{
    image?: ImageWithAlt;
    caption?: string;
    _type: "reelPhoto";
    _key: string;
  }>;
  logosHeading?: {
    start?: string;
    emphasis?: string;
  };
  why?: {
    eyebrow?: string;
    heading?: string;
    emphasis?: string;
    statement?: string;
    buttons?: Array<{
      _key: string;
    } & LinkItem>;
  };
  stats?: Array<{
    _key: string;
  } & Stat>;
  standards?: {
    title?: string;
    items?: Array<string>;
  };
  capabilities?: SectionIntro;
  industries?: SectionIntro;
  careers?: SectionIntro;
  insights?: SectionIntro;
  locations?: SectionIntro;
  ecosystem?: SectionIntro;
  contact?: SectionIntro;
  featuredInsight?: InsightReference;
  seo?: Seo;
};

export type InsightCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "insightCategory";
};

export type Insight = {
  _id: string;
  _type: "insight";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  allowSlugChange?: boolean;
  summary?: string;
  category?: InsightCategoryReference;
  type?: "Perspective" | "Guide" | "Explainer" | "Field notes";
  publishedAt?: string;
  author?: string;
  photo?: ImageWithAlt;
  takeaways?: Array<string>;
  body?: ArticleBody;
  featured?: boolean;
  order?: number;
  capabilities?: Array<{
    _key: string;
  } & CapabilityReference>;
  industries?: Array<{
    _key: string;
  } & IndustryReference>;
  contactTopic?: "cap-data" | "cap-sap" | "cap-ai" | "cap-flow" | "cap-code" | "capability-center" | "careers";
  related?: LinkItem;
  seo?: Seo;
};

export type InsightCategory = {
  _id: string;
  _type: "insightCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  order?: number;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  careersEmail?: string;
  phone?: string;
  social?: Array<{
    platform?: "linkedin" | "instagram" | "x" | "facebook" | "youtube";
    url?: string;
    _type: "socialProfile";
    _key: string;
  }>;
  ctaPrimaryLabel?: string;
  ctaSecondaryLabel?: string;
  footerLine?: string;
  approvedJobBoards?: Array<string>;
  seo?: Seo;
};

export type ChipGroup = {
  _type: "chipGroup";
  title?: string;
  items?: Array<string>;
};

export type FeatureItem = {
  _type: "featureItem";
  title?: string;
  text?: string;
};

export type ProblemRow = {
  _type: "problemRow";
  challenge?: string;
  answer?: string;
};

export type FaqItem = {
  _type: "faqItem";
  question?: string;
  answer?: TextBlock;
};

export type Callout = {
  _type: "callout";
  text?: string;
};

export type Table = {
  _type: "table";
  rows?: Array<{
    cells?: Array<string>;
    _type: "tableRow";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Problems | Offerings | Stack | SanityImageAssetReference | EcosystemCompany | SanityImageCrop | SanityImageHotspot | ClientLogo | IndustryReference | CapabilityReference | CaseStudy | Seo | TextBlock | ImageWithAlt | Slug | LocationReference | SanityFileAssetReference | Opportunity | ArticleBody | Location | LinkItem | Capability | Industry | Stat | PageSettings | SectionIntro | PageHero | InsightReference | HomePage | InsightCategoryReference | Insight | InsightCategory | SiteSettings | ChipGroup | FeatureItem | ProblemRow | FaqItem | Callout | Table | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

// Source: ../site/src/sanity/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings" && _id == "siteSettings"]{ ..., "seo": seo{ ..., "image": image{  ...,  "asset": asset->{    _id,    url,    extension,    "width": metadata.dimensions.width,    "height": metadata.dimensions.height  }} } }
export type SiteSettingsQueryResult = Array<{
  _id: "siteSettings";
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  careersEmail?: string;
  phone?: string;
  social?: Array<{
    platform?: "facebook" | "instagram" | "linkedin" | "x" | "youtube";
    url?: string;
    _type: "socialProfile";
    _key: string;
  }>;
  ctaPrimaryLabel?: string;
  ctaSecondaryLabel?: string;
  footerLine?: string;
  approvedJobBoards?: Array<string>;
  seo: {
    _type: "seo";
    title?: string;
    description?: string;
    image: {
      asset: {
        _id: string;
        url: string | null;
        extension: string | null;
        width: number | null;
        height: number | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noindex?: boolean;
  } | null;
}>;

// Source: ../site/src/sanity/queries.ts
// Variable: homePageQuery
// Query: *[_type == "homePage" && _id == "homePage"]{    ...,    reel[]{ ..., "image": image{  ...,  "asset": asset->{    _id,    url,    extension,    "width": metadata.dimensions.width,    "height": metadata.dimensions.height  }} },    "featuredInsight": featuredInsight._ref,    "seo": seo{ ..., "image": image{  ...,  "asset": asset->{    _id,    url,    extension,    "width": metadata.dimensions.width,    "height": metadata.dimensions.height  }} }  }
export type HomePageQueryResult = Array<{
  _id: "homePage";
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    badge?: string;
    heading?: string;
    highlight?: string;
    lede?: string;
    points?: Array<string>;
    careersPrompt?: string;
  };
  reel: Array<{
    image: {
      _type: "imageWithAlt";
      asset: {
        _id: string;
        url: string | null;
        extension: string | null;
        width: number | null;
        height: number | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      decorative?: boolean;
    } | null;
    caption?: string;
    _type: "reelPhoto";
    _key: string;
  }> | null;
  logosHeading?: {
    start?: string;
    emphasis?: string;
  };
  why?: {
    eyebrow?: string;
    heading?: string;
    emphasis?: string;
    statement?: string;
    buttons?: Array<{
      _key: string;
    } & LinkItem>;
  };
  stats?: Array<{
    _key: string;
  } & Stat>;
  standards?: {
    title?: string;
    items?: Array<string>;
  };
  capabilities?: SectionIntro;
  industries?: SectionIntro;
  careers?: SectionIntro;
  insights?: SectionIntro;
  locations?: SectionIntro;
  ecosystem?: SectionIntro;
  contact?: SectionIntro;
  featuredInsight: string | null;
  seo: {
    _type: "seo";
    title?: string;
    description?: string;
    image: {
      asset: {
        _id: string;
        url: string | null;
        extension: string | null;
        width: number | null;
        height: number | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noindex?: boolean;
  } | null;
}>;

// Source: ../site/src/sanity/queries.ts
// Variable: pageSettingsQuery
// Query: *[_type == "pageSettings"]{    ...,    hero{ ..., "photo": photo{  ...,  "asset": asset->{    _id,    url,    extension,    "width": metadata.dimensions.width,    "height": metadata.dimensions.height  }} },    "seo": seo{ ..., "image": image{  ...,  "asset": asset->{    _id,    url,    extension,    "width": metadata.dimensions.width,    "height": metadata.dimensions.height  }} }  }
export type PageSettingsQueryResult = Array<{
  _id: string;
  _type: "pageSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  page?: string;
  hero: {
    _type: "pageHero";
    eyebrow?: string;
    title?: string;
    lede?: string;
    points?: Array<string>;
    photo: {
      _type: "imageWithAlt";
      asset: {
        _id: string;
        url: string | null;
        extension: string | null;
        width: number | null;
        height: number | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      decorative?: boolean;
    } | null;
  } | null;
  faqIntro?: SectionIntro;
  faq?: Array<{
    _key: string;
  } & FaqItem>;
  seo: {
    _type: "seo";
    title?: string;
    description?: string;
    image: {
      asset: {
        _id: string;
        url: string | null;
        extension: string | null;
        width: number | null;
        height: number | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noindex?: boolean;
  } | null;
}>;

// Source: ../site/src/sanity/queries.ts
// Variable: capabilitiesQuery
// Query: *[_type == "capability"]{    ...,    "slug": slug.current,    "photo": photo{  ...,  "asset": asset->{    _id,    url,    extension,    "width": metadata.dimensions.width,    "height": metadata.dimensions.height  }},    industryNotes[]{ ..., "industry": industry._ref },    "seo": seo{ ..., "image": image{  ...,  "asset": asset->{    _id,    url,    extension,    "width": metadata.dimensions.width,    "height": metadata.dimensions.height  }} }  }
export type CapabilitiesQueryResult = Array<{
  _id: string;
  _type: "capability";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  heading?: string;
  descriptor?: string;
  slug: string | null;
  line?: string;
  photo: {
    _type: "imageWithAlt";
    asset: {
      _id: string;
      url: string | null;
      extension: string | null;
      width: number | null;
      height: number | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    decorative?: boolean;
  } | null;
  pageTitle?: string;
  lede?: string;
  points?: Array<string>;
  problems?: Problems;
  offerings?: Offerings;
  stack?: Stack;
  outcomes?: Array<{
    _key: string;
  } & Stat>;
  faq?: Array<{
    _key: string;
  } & FaqItem>;
  team?: string;
  howItWorks?: {
    heading?: string;
    intro?: string;
    steps?: Array<{
      title?: string;
      text?: string;
      note?: string;
      _type: "processStep";
      _key: string;
    }>;
  };
  industryNotes: Array<{
    industry: string | null;
    text?: string;
    _type: "industryNote";
    _key: string;
  }> | null;
  seo: {
    _type: "seo";
    title?: string;
    description?: string;
    image: {
      asset: {
        _id: string;
        url: string | null;
        extension: string | null;
        width: number | null;
        height: number | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noindex?: boolean;
  } | null;
}>;

// Source: ../site/src/sanity/queries.ts
// Variable: industriesQuery
// Query: *[_type == "industry"]{    ...,    "slug": slug.current,    "photo": photo{  ...,  "asset": asset->{    _id,    url,    extension,    "width": metadata.dimensions.width,    "height": metadata.dimensions.height  }},    capabilityNotes[]{ ..., "capability": capability._ref },    "seo": seo{ ..., "image": image{  ...,  "asset": asset->{    _id,    url,    extension,    "width": metadata.dimensions.width,    "height": metadata.dimensions.height  }} }  }
export type IndustriesQueryResult = Array<{
  _id: string;
  _type: "industry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug: string | null;
  short?: string;
  summary?: string;
  photo: {
    _type: "imageWithAlt";
    asset: {
      _id: string;
      url: string | null;
      extension: string | null;
      width: number | null;
      height: number | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    decorative?: boolean;
  } | null;
  hero?: string;
  lede?: string;
  points?: Array<string>;
  challenge?: string;
  build?: string;
  outcome?: string;
  metric?: Stat;
  problems?: Problems;
  offerings?: Offerings;
  stack?: Stack;
  outcomes?: Array<{
    _key: string;
  } & Stat>;
  faq?: Array<{
    _key: string;
  } & FaqItem>;
  capabilityNotes: Array<{
    capability: string | null;
    text?: string;
    _type: "capabilityNote";
    _key: string;
  }> | null;
  seo: {
    _type: "seo";
    title?: string;
    description?: string;
    image: {
      asset: {
        _id: string;
        url: string | null;
        extension: string | null;
        width: number | null;
        height: number | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noindex?: boolean;
  } | null;
}>;

// Source: ../site/src/sanity/queries.ts
// Variable: locationsQuery
// Query: *[_type == "location"] | order(order asc)
export type LocationsQueryResult = Array<{
  _id: string;
  _type: "location";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  city?: string;
  short?: string;
  country?: string;
  role?: string;
  text?: string;
  address?: string;
  phone?: string;
  email?: string;
  timeZone?: string;
  locale?: string;
  position?: {
    lat?: number;
    lon?: number;
  };
  link?: LinkItem;
  order?: number;
}>;

// Source: ../site/src/sanity/queries.ts
// Variable: articlesQuery
// Query: *[_type == "insight" && defined(slug.current)] | order(order asc){    ...,    "slug": slug.current,    "category": category->{ title, "slug": slug.current },    "photo": photo{  ...,  "asset": asset->{    _id,    url,    extension,    "width": metadata.dimensions.width,    "height": metadata.dimensions.height  }},    body[]{ ..., _type == "imageWithAlt" => {  ...,  "asset": asset->{    _id,    url,    extension,    "width": metadata.dimensions.width,    "height": metadata.dimensions.height  }} },    "capabilities": capabilities[]._ref,    "industries": industries[]._ref,    "seo": seo{ ..., "image": image{  ...,  "asset": asset->{    _id,    url,    extension,    "width": metadata.dimensions.width,    "height": metadata.dimensions.height  }} }  }
export type ArticlesQueryResult = Array<{
  _id: string;
  _type: "insight";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug: string | null;
  allowSlugChange?: boolean;
  summary?: string;
  category: {
    title: string | null;
    slug: string | null;
  } | null;
  type?: "Explainer" | "Field notes" | "Guide" | "Perspective";
  publishedAt?: string;
  author?: string;
  photo: {
    _type: "imageWithAlt";
    asset: {
      _id: string;
      url: string | null;
      extension: string | null;
      width: number | null;
      height: number | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    decorative?: boolean;
  } | null;
  takeaways?: Array<string>;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    _key: string;
    _type: "callout";
    text?: string;
  } | {
    _key: string;
    _type: "imageWithAlt";
    asset: {
      _id: string;
      url: string | null;
      extension: string | null;
      width: number | null;
      height: number | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    decorative?: boolean;
  } | {
    _key: string;
    _type: "table";
    rows?: Array<{
      cells?: Array<string>;
      _type: "tableRow";
      _key: string;
    }>;
  }> | null;
  featured?: boolean;
  order?: number;
  capabilities: Array<string> | null;
  industries: Array<string> | null;
  contactTopic?: "cap-ai" | "cap-code" | "cap-data" | "cap-flow" | "cap-sap" | "capability-center" | "careers";
  related?: LinkItem;
  seo: {
    _type: "seo";
    title?: string;
    description?: string;
    image: {
      asset: {
        _id: string;
        url: string | null;
        extension: string | null;
        width: number | null;
        height: number | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noindex?: boolean;
  } | null;
}>;

// Source: ../site/src/sanity/queries.ts
// Variable: articleCategoriesQuery
// Query: *[_type == "insightCategory"] | order(order asc){    _id,    title,    "slug": slug.current,    order  }
export type ArticleCategoriesQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  order: number | null;
}>;

// Source: ../site/src/sanity/queries.ts
// Variable: opportunitiesQuery
// Query: *[_type == "opportunity" && defined(slug.current)] | order(postedAt desc){    ...,    "slug": slug.current,    "capability": capability._ref,    "locations": locations[]._ref,    description[]{ ..., _type == "imageWithAlt" => {  ...,  "asset": asset->{    _id,    url,    extension,    "width": metadata.dimensions.width,    "height": metadata.dimensions.height  }} },    "jdPdf": jdPdf.asset->{ _id, url, extension, size, originalFilename },    "seo": seo{ ..., "image": image{  ...,  "asset": asset->{    _id,    url,    extension,    "width": metadata.dimensions.width,    "height": metadata.dimensions.height  }} }  }
export type OpportunitiesQueryResult = Array<{
  _id: string;
  _type: "opportunity";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  status?: "closed" | "open";
  slug: string | null;
  allowSlugChange?: boolean;
  reference?: string;
  team?: "capability" | "client-partnership";
  capability: string | null;
  locations: Array<string> | null;
  place?: string;
  remote?: boolean;
  workMode?: "Hybrid" | "On-site" | "Remote";
  employmentType?: "Fixed-term" | "Full-time" | "Internship" | "Part-time";
  experience?: string;
  postedAt?: string;
  closesAt?: string;
  summary?: string;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    _key: string;
    _type: "callout";
    text?: string;
  } | {
    _key: string;
    _type: "imageWithAlt";
    asset: {
      _id: string;
      url: string | null;
      extension: string | null;
      width: number | null;
      height: number | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    decorative?: boolean;
  } | {
    _key: string;
    _type: "table";
    rows?: Array<{
      cells?: Array<string>;
      _type: "tableRow";
      _key: string;
    }>;
  }> | null;
  requirements?: Array<string>;
  skills?: Array<string>;
  jdPdf: {
    _id: string;
    url: string | null;
    extension: string | null;
    size: number | null;
    originalFilename: string | null;
  } | null;
  applyMethod?: "email" | "link";
  applyEmail?: string;
  applyUrl?: string;
  seo: {
    _type: "seo";
    title?: string;
    description?: string;
    image: {
      asset: {
        _id: string;
        url: string | null;
        extension: string | null;
        width: number | null;
        height: number | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noindex?: boolean;
  } | null;
}>;

// Source: ../site/src/sanity/queries.ts
// Variable: caseStudiesQuery
// Query: *[_type == "caseStudy" && defined(slug.current)] | order(publishedAt desc){    ...,    "slug": slug.current,    "clientPermission": clientPermission{ confirmed },    "clientName": select(      clientPermission.confirmed == true => clientPermission.clientName    ),    "industry": industry._ref,    "capabilities": capabilities[]._ref,    "photo": photo{  ...,  "asset": asset->{    _id,    url,    extension,    "width": metadata.dimensions.width,    "height": metadata.dimensions.height  }},    "seo": seo{ ..., "image": image{  ...,  "asset": asset->{    _id,    url,    extension,    "width": metadata.dimensions.width,    "height": metadata.dimensions.height  }} }  }
export type CaseStudiesQueryResult = Array<{
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug: string | null;
  allowSlugChange?: boolean;
  anonymisedDescriptor?: string;
  clientPermission: {
    confirmed: boolean | null;
  } | null;
  industry: string | null;
  capabilities: Array<string> | null;
  summary?: string;
  photo: {
    _type: "imageWithAlt";
    asset: {
      _id: string;
      url: string | null;
      extension: string | null;
      width: number | null;
      height: number | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    decorative?: boolean;
  } | null;
  challenge?: TextBlock;
  approach?: TextBlock;
  outcomes?: Array<{
    _key: string;
  } & Stat>;
  quotes?: Array<{
    text?: string;
    attribution?: string;
    confirmed?: boolean;
    confirmedBy?: string;
    confirmedOn?: string;
    evidence?: string;
    _type: "quote";
    _key: string;
  }>;
  publishedAt?: string;
  seo: {
    _type: "seo";
    title?: string;
    description?: string;
    image: {
      asset: {
        _id: string;
        url: string | null;
        extension: string | null;
        width: number | null;
        height: number | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noindex?: boolean;
  } | null;
  clientName: string | null;
}>;

// Source: ../site/src/sanity/queries.ts
// Variable: clientLogosQuery
// Query: *[_type == "clientLogo"] | order(order asc){ ..., "logo": logo{  ...,  "asset": asset->{    _id,    url,    extension,    "width": metadata.dimensions.width,    "height": metadata.dimensions.height  }} }
export type ClientLogosQueryResult = Array<{
  _id: string;
  _type: "clientLogo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  row?: "banking" | "telecom-healthcare-energy";
  logo: {
    asset: {
      _id: string;
      url: string | null;
      extension: string | null;
      width: number | null;
      height: number | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  permissionConfirmed?: boolean;
  confirmedBy?: string;
  confirmedOn?: string;
  evidence?: string;
  order?: number;
}>;

// Source: ../site/src/sanity/queries.ts
// Variable: ecosystemQuery
// Query: *[_type == "ecosystemCompany"] | order(order asc){ ..., "logo": logo{  ...,  "asset": asset->{    _id,    url,    extension,    "width": metadata.dimensions.width,    "height": metadata.dimensions.height  }} }
export type EcosystemQueryResult = Array<{
  _id: string;
  _type: "ecosystemCompany";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  focus?: string;
  line?: string;
  logo: {
    asset: {
      _id: string;
      url: string | null;
      extension: string | null;
      width: number | null;
      height: number | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  url?: string;
  relationshipConfirmed?: boolean;
  confirmedBy?: string;
  confirmedOn?: string;
  evidence?: string;
  order?: number;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    "\n  *[_type == \"siteSettings\" && _id == \"siteSettings\"]{ ..., \"seo\": seo{ ..., \"image\": image{\n  ...,\n  \"asset\": asset->{\n    _id,\n    url,\n    extension,\n    \"width\": metadata.dimensions.width,\n    \"height\": metadata.dimensions.height\n  }\n} } }\n": SiteSettingsQueryResult;
    "\n  *[_type == \"homePage\" && _id == \"homePage\"]{\n    ...,\n    reel[]{ ..., \"image\": image{\n  ...,\n  \"asset\": asset->{\n    _id,\n    url,\n    extension,\n    \"width\": metadata.dimensions.width,\n    \"height\": metadata.dimensions.height\n  }\n} },\n    \"featuredInsight\": featuredInsight._ref,\n    \"seo\": seo{ ..., \"image\": image{\n  ...,\n  \"asset\": asset->{\n    _id,\n    url,\n    extension,\n    \"width\": metadata.dimensions.width,\n    \"height\": metadata.dimensions.height\n  }\n} }\n  }\n": HomePageQueryResult;
    "\n  *[_type == \"pageSettings\"]{\n    ...,\n    hero{ ..., \"photo\": photo{\n  ...,\n  \"asset\": asset->{\n    _id,\n    url,\n    extension,\n    \"width\": metadata.dimensions.width,\n    \"height\": metadata.dimensions.height\n  }\n} },\n    \"seo\": seo{ ..., \"image\": image{\n  ...,\n  \"asset\": asset->{\n    _id,\n    url,\n    extension,\n    \"width\": metadata.dimensions.width,\n    \"height\": metadata.dimensions.height\n  }\n} }\n  }\n": PageSettingsQueryResult;
    "\n  *[_type == \"capability\"]{\n    ...,\n    \"slug\": slug.current,\n    \"photo\": photo{\n  ...,\n  \"asset\": asset->{\n    _id,\n    url,\n    extension,\n    \"width\": metadata.dimensions.width,\n    \"height\": metadata.dimensions.height\n  }\n},\n    industryNotes[]{ ..., \"industry\": industry._ref },\n    \"seo\": seo{ ..., \"image\": image{\n  ...,\n  \"asset\": asset->{\n    _id,\n    url,\n    extension,\n    \"width\": metadata.dimensions.width,\n    \"height\": metadata.dimensions.height\n  }\n} }\n  }\n": CapabilitiesQueryResult;
    "\n  *[_type == \"industry\"]{\n    ...,\n    \"slug\": slug.current,\n    \"photo\": photo{\n  ...,\n  \"asset\": asset->{\n    _id,\n    url,\n    extension,\n    \"width\": metadata.dimensions.width,\n    \"height\": metadata.dimensions.height\n  }\n},\n    capabilityNotes[]{ ..., \"capability\": capability._ref },\n    \"seo\": seo{ ..., \"image\": image{\n  ...,\n  \"asset\": asset->{\n    _id,\n    url,\n    extension,\n    \"width\": metadata.dimensions.width,\n    \"height\": metadata.dimensions.height\n  }\n} }\n  }\n": IndustriesQueryResult;
    "\n  *[_type == \"location\"] | order(order asc)\n": LocationsQueryResult;
    "\n  *[_type == \"insight\" && defined(slug.current)] | order(order asc){\n    ...,\n    \"slug\": slug.current,\n    \"category\": category->{ title, \"slug\": slug.current },\n    \"photo\": photo{\n  ...,\n  \"asset\": asset->{\n    _id,\n    url,\n    extension,\n    \"width\": metadata.dimensions.width,\n    \"height\": metadata.dimensions.height\n  }\n},\n    body[]{ ..., _type == \"imageWithAlt\" => {\n  ...,\n  \"asset\": asset->{\n    _id,\n    url,\n    extension,\n    \"width\": metadata.dimensions.width,\n    \"height\": metadata.dimensions.height\n  }\n} },\n    \"capabilities\": capabilities[]._ref,\n    \"industries\": industries[]._ref,\n    \"seo\": seo{ ..., \"image\": image{\n  ...,\n  \"asset\": asset->{\n    _id,\n    url,\n    extension,\n    \"width\": metadata.dimensions.width,\n    \"height\": metadata.dimensions.height\n  }\n} }\n  }\n": ArticlesQueryResult;
    "\n  *[_type == \"insightCategory\"] | order(order asc){\n    _id,\n    title,\n    \"slug\": slug.current,\n    order\n  }\n": ArticleCategoriesQueryResult;
    "\n  *[_type == \"opportunity\" && defined(slug.current)] | order(postedAt desc){\n    ...,\n    \"slug\": slug.current,\n    \"capability\": capability._ref,\n    \"locations\": locations[]._ref,\n    description[]{ ..., _type == \"imageWithAlt\" => {\n  ...,\n  \"asset\": asset->{\n    _id,\n    url,\n    extension,\n    \"width\": metadata.dimensions.width,\n    \"height\": metadata.dimensions.height\n  }\n} },\n    \"jdPdf\": jdPdf.asset->{ _id, url, extension, size, originalFilename },\n    \"seo\": seo{ ..., \"image\": image{\n  ...,\n  \"asset\": asset->{\n    _id,\n    url,\n    extension,\n    \"width\": metadata.dimensions.width,\n    \"height\": metadata.dimensions.height\n  }\n} }\n  }\n": OpportunitiesQueryResult;
    "\n  *[_type == \"caseStudy\" && defined(slug.current)] | order(publishedAt desc){\n    ...,\n    \"slug\": slug.current,\n    \"clientPermission\": clientPermission{ confirmed },\n    \"clientName\": select(\n      clientPermission.confirmed == true => clientPermission.clientName\n    ),\n    \"industry\": industry._ref,\n    \"capabilities\": capabilities[]._ref,\n    \"photo\": photo{\n  ...,\n  \"asset\": asset->{\n    _id,\n    url,\n    extension,\n    \"width\": metadata.dimensions.width,\n    \"height\": metadata.dimensions.height\n  }\n},\n    \"seo\": seo{ ..., \"image\": image{\n  ...,\n  \"asset\": asset->{\n    _id,\n    url,\n    extension,\n    \"width\": metadata.dimensions.width,\n    \"height\": metadata.dimensions.height\n  }\n} }\n  }\n": CaseStudiesQueryResult;
    "\n  *[_type == \"clientLogo\"] | order(order asc){ ..., \"logo\": logo{\n  ...,\n  \"asset\": asset->{\n    _id,\n    url,\n    extension,\n    \"width\": metadata.dimensions.width,\n    \"height\": metadata.dimensions.height\n  }\n} }\n": ClientLogosQueryResult;
    "\n  *[_type == \"ecosystemCompany\"] | order(order asc){ ..., \"logo\": logo{\n  ...,\n  \"asset\": asset->{\n    _id,\n    url,\n    extension,\n    \"width\": metadata.dimensions.width,\n    \"height\": metadata.dimensions.height\n  }\n} }\n": EcosystemQueryResult;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}

